name: Generate Emoji Code
run-name: Generating Golang emoji lookup tables
on:
  schedule:
    - cron: '0 0 1 * *' # Run once per month
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  monthly:
    name: Update Emoji data monthly
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v6
    - name: 'Setup Go'
      uses: actions/setup-go@v6
      with:
          go-version-file: 'go.mod'
    - name: Build and Run Codegen
      run: |
        go install ./emoji_codegen
        go generate ./...
    - name: Set version
      id: tag
      run: echo "version=$(date +'%Y.%-m')" >> $GITHUB_OUTPUT
    - uses: EndBug/add-and-commit@v10
      id: commit
      with:
        message: "monthly: update emoji data"
        add: 'emoji_gen.go'
        committer_name: GitHub Actions
        committer_email: actions@github.com
        tag: v${{ steps.tag.outputs.version }}
    - name: Release
      uses: softprops/action-gh-release@v2
      if: steps.commit.outputs.tag_pushed
      with:
        tag_name: v${{ steps.tag.outputs.version }}
